const peopleData = [
  {
    sound: "assets/sound_pieces/yuri_00.mp3",
    name: "yuri_00",
    color: paletteYuri,
    title: "Chew harder and you'll see what happens",
    image: "assets/images/500x500px Icon.png",
  },
  {
    sound: "assets/sound_pieces/yuri_01.mp3",
    name: "yuri_01",
    color: paletteYuri,
    title: "Radio narration on climate change",
    image: "assets/images/500x500px Icon.png",
  },
  {
    sound: "assets/sound_pieces/yuri_02.mp3",
    name: "yuri_02",
    color: paletteYuri,
    title: "Leaving things on",
    image: "assets/images/500x500px Icon.png",
  },
  {
    sound: "assets/sound_pieces/yuri_03.mp3",
    name: "yuri_03",
    color: paletteYuri,
    title: "single use plastic",
    image: "assets/images/500x500px Icon.png",
  },
  {
    sound: "assets/sound_pieces/POLICE STATE-hani.mp3",
    name: "hani-00",
    color: paletteHani,
    title: "POLICE STATE",
    image: "assets/images/Hani.jpg",
  },
  {
    sound: "assets/sound_pieces/ROBOT UTOPIA W-hani.mp3",
    name: "hani-01",
    color: paletteHani,
    title: "ROBOT UTOPIA",
    image: "assets/images/Hani.jpg",
  },
  {
    sound: "assets/sound_pieces/Bitter [Waste] Hani draft.mp3",
    name: "hani-02",
    color: paletteHani,
    title: "Bitter",
    image: "assets/images/Hani.jpg",
  },
  {
    sound: "assets/sound_pieces/UPPER ATMOSPHERE CONTAMINANT.mp3",
    name: "hani-03",
    color: paletteHani,
    title: "UPPER ATMOSPHERE CONTAMINANT",
    image: "assets/images/Hani.jpg",
  },
  {
    sound: "assets/sound_pieces/ben_00.mp3",
    name: "ben",
    color: paletteKevin,
    title: "Ecological flaneur",
    image: "assets/images/Ben_image.jpeg",
  },
  {
    sound: "assets/sound_pieces/kevin_00.mp3",
    name: "kevin",
    color: paletteKevin,
    title: "Jeroan(innards)",
    image: "assets/images/Kevin_image.jpg",
  },
  {
    sound: "assets/sound_pieces/max_00.mp3",
    name: "max",
    color: paletteMax,
    title: "On the way to the show",
    image: "assets/images/Max_image.png",
  },
  {
    sound: "assets/sound_pieces/alex_00.mp3",
    name: "alex_00",
    color: paletteAlex,
    title: "Gullet ",
    image: "assets/images/alex.png",
  },
  {
    sound: "assets/sound_pieces/6 hour parsley net.mpeg",
    name: "alex_01",
    color: paletteAlex,
    title: "6 HOUR PARSLET NET ",
    image: "assets/images/alex.png",
  },
  {
    sound: "assets/sound_pieces/cally_00.mp3",
    name: "cally",
    color: paletteCally,
    title: "Crypto Quarry",
    image: "assets/images/Cally.gif",
  },
  {
    sound:
      "assets/sound_pieces/DIE TODAY SO NATURE CAN LIVE TOMORROW 10.27.37.mp3",
    name: "Rosie",
    color: paletteRosie,
    title: "DIE TODAY SO NATURE CAN LIVE TOMORROW",
    image: "assets/images/rosy image.png",
  },
  {
    sound: "assets/sound_pieces/thetuningofsoils.mp3",
    name: "Joey_00",
    color: paletteJoey,
    title: "The tuning of soils",
    image: "assets/images/joey_image.jpg",
  },
  {
    sound: "assets/sound_pieces/depletedrocksandbygone.mp3",
    name: "Joey_01",
    color: paletteJoey,
    title: " Depleted rocks and bygone",
    image: "assets/images/cracked-ground-1.jpg",
  },
  // {
  //   sound: "assets/sound_pieces/",
  //   name: "Kuba",
  //   color: paletteKuba,
  //   title: "NEED PIECE",
  // },
  {
    sound: "assets/sound_pieces/FINAL VIraj - MUSIC IS OVER [Nightlife].mp3",
    name: "Viraj",
    color: paletteViraj,
    title: "THE MUSIC OVER",
    image: "assets/images/Viraj_Image.jpg",
  },
  {
    sound: "assets/sound_pieces/Twin (Draft) [TRANSPORT] - Dan W.mp3",
    name: "Dan",
    color: paletteDan,
    title: "Twin",
    image: "assets/images/joey_image.jpg",
  },
  {
    sound: "assets/sound_pieces/Warmer (draft) [Climate] - kamil.mp3",
    name: "Kamil",
    color: paletteKamil,
    title: "Warmer",
    image: "assets/images/Kamil.jpeg",
  },
  {
    sound: "assets/sound_pieces/Zhi Jiao [Education]-Peter.mp3",
    name: "Peter",
    color: palettePeter,
    title: "Zhi Jiao",
    image: "assets/images/Peter Lai.JPG",
  },
  {
    sound: "assets/sound_pieces/Carbon2.mp3",
    name: "Lewis",
    color: paletteLewis,
    titel: "carbon",
    image: "assets/images/VectorPainting3.png",
  },
];
